In [63]:
import numpy as np
import pandas as pd

df_data = pd.read_csv("data_analytics.csv")
df_data.head()

,Event Date,App Apple ID,Subscription Name,Standard Subscription Duration,Promotional Offer Name,Promotional Offer ID,Subscription Offer Type,Subscription Offer Duration,Marketing Opt-In Duration,Customer Currency,Proceeds Currency,Device,Country,Subscriber ID,Subscriber ID Reset,Refund,Purchase Date,Units
0,2019-07-15,1,weekly 9.99 + 7D trial,7 Days,NaN,NaN,Free Trial,7 Days,NaN,IDR,IDR,iPhone,ID,223411322456765433,NaN,NaN,NaN,1
1,2019-07-15,1,weekly 9.99 + 7D trial,7 Days,NaN,NaN,Free Trial,7 Days,NaN,USD,USD,iPhone,US,223411322456765434,NaN,NaN,NaN,1
2,2019-07-15,1,weekly 9.99 + 7D trial,7 Days,NaN,NaN,Free Trial,7 Days,NaN,INR,INR,iPhone,IN,223411322456765435,NaN,NaN,NaN,1
3,2019-07-15,1,weekly 9.99 + 7D trial,7 Days,NaN,NaN,Free Trial,7 Days,NaN,GBP,GBP,iPhone,GB,223411322456765437,NaN,NaN,NaN,1
4,2019-07-15,1,weekly 9.99 + 7D trial,7 Days,NaN,NaN,Free Trial,7 Days,NaN,INR,INR,iPhone,IN,223411322456765438,NaN,NaN,NaN,1

In [64]:
#delete not informative columns:

del df_data['App Apple ID']
del df_data['Subscription Name']
del df_data['Standard Subscription Duration']
del df_data['Promotional Offer Name']
del df_data['Marketing Opt-In Duration']
del df_data['Promotional Offer ID']
del df_data['Subscriber ID Reset']
del df_data['Purchase Date']
del df_data['Refund']
del df_data['Units']

df_data

,Event Date,Subscription Offer Type,Subscription Offer Duration,Customer Currency,Proceeds Currency,Device,Country,Subscriber ID
0,2019-07-15,Free Trial,7 Days,IDR,IDR,iPhone,ID,223411322456765433
1,2019-07-15,Free Trial,7 Days,USD,USD,iPhone,US,223411322456765434
2,2019-07-15,Free Trial,7 Days,INR,INR,iPhone,IN,223411322456765435
3,2019-07-15,Free Trial,7 Days,GBP,GBP,iPhone,GB,223411322456765437
4,2019-07-15,Free Trial,7 Days,INR,INR,iPhone,IN,223411322456765438
...,...,...,...,...,...,...,...,...
2375,2019-08-24,NaN,NaN,MYR,MYR,iPhone,MY,223411322456766566
2376,2019-08-24,NaN,NaN,USD,USD,iPhone,US,223411322456766569
2377,2019-08-24,NaN,NaN,INR,INR,iPhone,IN,223411322456766571
2378,2019-08-24,NaN,NaN,USD,USD,iPhone,US,223411322456766572
2379,2019-08-24,NaN,NaN,MYR,MYR,iPhone,MY,223411322456766573

In [65]:
subscribers = df_data['Subscriber ID'].tolist()

#unique IDs:
subscribers = set(subscribers)
subscribers = list(subscribers)

df_data.rename(columns={'Subscriber ID': 'Subscriber_ID'}, inplace=True)
df_data

,Event Date,Subscription Offer Type,Subscription Offer Duration,Customer Currency,Proceeds Currency,Device,Country,Subscriber_ID
0,2019-07-15,Free Trial,7 Days,IDR,IDR,iPhone,ID,223411322456765433
1,2019-07-15,Free Trial,7 Days,USD,USD,iPhone,US,223411322456765434
2,2019-07-15,Free Trial,7 Days,INR,INR,iPhone,IN,223411322456765435
3,2019-07-15,Free Trial,7 Days,GBP,GBP,iPhone,GB,223411322456765437
4,2019-07-15,Free Trial,7 Days,INR,INR,iPhone,IN,223411322456765438
...,...,...,...,...,...,...,...,...
2375,2019-08-24,NaN,NaN,MYR,MYR,iPhone,MY,223411322456766566
2376,2019-08-24,NaN,NaN,USD,USD,iPhone,US,223411322456766569
2377,2019-08-24,NaN,NaN,INR,INR,iPhone,IN,223411322456766571
2378,2019-08-24,NaN,NaN,USD,USD,iPhone,US,223411322456766572
2379,2019-08-24,NaN,NaN,MYR,MYR,iPhone,MY,223411322456766573

In [66]:
LTVs = []
price = 9.99
apple_store_tax = 0.3

for ID in subscribers:
    weeks = len(df_data[df_data.Subscriber_ID == ID]['Subscriber_ID'])
    LTV = (weeks-1)*(1-apple_store_tax)*price
    LTVs.append(LTV)

LTVs

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 34.965,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 13.985999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 27.971999999999998,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 20.978999999999996,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 13.985999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 6.992999999999999,
 ...]

In [67]:
LTV_df = pd.DataFrame({'Subscriber ID': subscribers, 'LTV': LTVs})
LTV_df

           Subscriber ID  LTV
0     223411322456766465  0.0
1     223411322456766466  0.0
2     223411322456766467  0.0
3     223411322456766469  0.0
4     223411322456766470  0.0
...                  ...  ...
1014  223411322456766457  0.0
1015  223411322456766459  0.0
1016  223411322456766460  0.0
1017  223411322456766461  0.0
1018  223411322456766462  0.0

[1019 rows x 2 columns]

In [68]:
LTV_df.to_csv("LTV.csv", index=False)